openapi: 3.0.0
info:
  title: Sample API
  version: 1.0.0
paths:
  /users:
    get:
      summary: Get a list of users
      description: Retrieve a list of users from the system
      responses:
        '200':
          description: A list of users
          content:
            application/json:
              example:
                - id: 1
                  username: john_doe
                  email: john@example.com
                - id: 2
                  username: jane_smith
                  email: jane@example.com
    post:
      summary: Create a new user
      description: Create a new user in the system
      requestBody:
        required: true
        content:
          application/json:
            example:
              username: new_user
              email: new_usdasdsdadasdasdasdasdasdas.com
      responses:
        '201':
          description: User created successfully
  /users/{userId}:
    get:
      summary: Get user by ID
      description: Retrieve a user by their ID
      parameters:
        - name: userId
          in: path
          required: true
          description: ID of the user to retrieve
          schema:
            type: integer
      responses:
        '200':
          description: The user with the specified ID
          content:
            application/json:
              example:
                id: 1
                username: john_doe
                email: john@example.com
        '404':
          description: User not found
