name: Get Changed Files on Push

on:
  push:
    branches:
      - main

jobs:
  get-changed-files:
    runs-on: ubuntu-latest

    outputs:
      id: changed-files
      value: ${{ steps.get-changed-files.outputs.changed_files }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Fetch latest changes
        run: git fetch --prune --unshallow

      - name: Get changed files
        id: get-changed-files
        run: |
          # Get the list of changed files
          CHANGED_FILES=$(git diff --name-only ${{ github.event.before }} ${{ github.sha }})
          echo "::set-output name=changed_files::$CHANGED_FILES"

  validate-openapi-definition:
    needs: get-changed-files
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Validate OpenAPI definition
        uses: char0n/swagger-editor-validate@v1
        with:
          swagger-editor-url: http://localhost/
          definition-file: ${{ needs.get-changed-files.outputs.changed_files }}
