name: Get Changed Files on Push

on: [ push ]

jobs:
  get-changed-files:
    runs-on: ubuntu-latest

    services:
      swagger-editor:
        image: swaggerapi/swagger-editor
        ports:
          - 80:8080
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Fetch latest changes
        run: git fetch --prune --unshallow

      - name: Get changed files
        id: get-changed-files
        run: |
          CHANGED_FILES=$(git diff --name-only ${{ github.event.before }} ${{ github.sha }})
          echo "changed_files=$CHANGED_FILES" >> $GITHUB_OUTPUT

      - name: Print changed files
        run: |
          CHANGED_FILE="${{ steps.get-changed-files.outputs.changed_files }}"
          echo "$CHANGED_FILE"

      - name: Validate OpenAPI definition
        if: ${{ endsWith(steps.get-changed-files.outputs.changed_files, '.yaml') }}
        uses: char0n/swagger-editor-validate@v1
        with:
          swagger-editor-url: http://localhost/
          definition-file: ${{ steps.get-changed-files.outputs.changed_files }}