name: Get Changed Files on Push

on: [ push ]

jobs:
  get-changed-files:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Fetch latest changes
        run: git fetch --prune --unshallow

      - name: Get changed files
        id: get-changed-files
        run: |
          CHANGED_FILES=$(git diff --name-only ${{ github.event.before }} ${{ github.sha }})
          echo "changed_files=$CHANGED_FILES" >> $GITHUB_OUTPUT

      - name: Print changed files
        run: |
          CHANGED_FILES="${{ steps.get-changed-files.outputs.changed_files }}"

          IFS=$'\n' read -r -a CHANGED_FILES_ARRAY <<< "$CHANGED_FILES"
          for file in "${CHANGED_FILES_ARRAY[@]}"; do
            echo "Changed file: $file"
          done
