name: Validate OpenAPI Definitions test

on: [ push ]

jobs:
  validated:
    runs-on: ubuntu-latest

    services:
      swagger-editor:
        image: swaggerapi/swagger-editor
        ports:
          - 80:8080

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Get changed files
        id: get-changed-files
        run: |
          # Get the list of changed files
          CHANGED_FILES=$(git diff --name-status main ${{ github.sha }})
          echo "::set-output name=changed_files::$CHANGED_FILES"

      - name: Validate OpenAPI definition
        uses: char0n/swagger-editor-validate@v1
        with:
          swagger-editor-url: http://localhost/
          definition-file: ${{ steps.get-changed-files.outputs.changed_files }}
