name: Validate OpenAPI Definitions test

on: [ push ]

jobs:
  validated:
    runs-on: ubuntu-latest

    services:
      swagger-editor:
        image: swaggerapi/swagger-editor
        ports:
          - 80:8080

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Get changed files
        id: get-changed-files
        run: |
          # Get the list of changed files
          CHANGED_FILES=$(git diff --name-status @{u} ${{ github.sha }})
          echo "::set-output name=changed_files::$CHANGED_FILES"

      - name: Print changed files
        run: |
          CHANGED_FILES="${{ steps.get-changed-files.outputs.changed_files }}"
          
          # Process each changed file
          IFS=$'\n' read -r -a CHANGED_FILES_ARRAY <<< "$CHANGED_FILES"
          for file in "${CHANGED_FILES_ARRAY[@]}"; do
            echo "Changed file: $file"
          done

      - name: Print changed files
        run: |
          CHANGED_FILES="${{ steps.get-changed-files.outputs.changed_files }}"

          # Process each changed file
          IFS=$'\n' read -r -a CHANGED_FILES_ARRAY <<< "$CHANGED_FILES"
          for file in "${CHANGED_FILES_ARRAY[@]}"; do
            echo "Changed file: $file"
          done
