name: Validate OpenAPI Definitions

on:
  push:
    branches:
      - main

jobs:
  validate:
    runs-on: ubuntu-latest
    services:
      swagger-editor:
        image: swaggerapi/swagger-editor
        ports:
          - 80:8080

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Validate OpenAPI definitions
        run: |
          for file in openapi.yaml openapi2.yaml openapi3.yaml; do
            echo "Validating $file"
            docker run -v $PWD:/app -w /app char0n/swagger-editor-validate:v1 --swagger-editor-url http://localhost/ --definition-file $file
          done
