on: push
name: Validate API swagger documentation
jobs:
  validate:

    runs-on: ubuntu-latest

    steps:
      - name: Get OpenAPI files
        id: getfiles
        uses: actions/checkout@v2
        run:  |
          echo 'FILE_LIST<<EOF' >> $GITHUB_ENV
          find lib -type f -iname "*openapi.yaml" >> $GITHUB_ENV
          echo 'EOF' >> $GITHUB_ENV
          
          FILES="$(find lib -type f -iname "*openapi.yaml")"
          echo "::set-output name=file_list::$FILES"
      - name: swagger-validator
        uses: mbowman100/swagger-validator-action@master
        if: env.FILE_COUNT != '0'
        with:
          files: ${{ env.FILE_LIST }}
