name: Validate OpenAPI Definitions

on: [push]

jobs:
  validate:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        definition-file:
          - openapi.yaml
          - openapi2.yaml
          - openapi3.yaml

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Validate OpenAPI definition
        uses: char0n/swagger-editor-validate@v1
        with:
          swagger-editor-url: http://localhost/
          definition-file: ${{ matrix.definition-file }}
