name: Validate OpenAPI Definitions

on: [ push ]

jobs:
  validate-definitions:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        definition-file:
          - path/to/definition1.yaml
          - path/to/definition2.yaml
          - path/to/definition3.yaml

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Validate OpenAPI definition
        run: |
          for file in ${{ matrix.definition-file }}; do
            echo "Validating $file"
            char0n/swagger-editor-validate@v1 --swagger-editor-url http://localhost/ --definition-file $file
          done
